### ISSUE TITLE
백준 7576 토마토 풀이 방법

### ISSUE THREAD

**Issue by saokiritoni** [GoormPyri/GoormPyri#27]
https://www.acmicpc.net/problem/7576

# 문제
철수의 토마토 농장에서는 토마토를 보관하는 큰 창고를 가지고 있다. 토마토는 아래의 그림과 같이 격자 모양 상자의 칸에 하나씩 넣어서 창고에 보관한다.

창고에 보관되는 토마토들 중에는 잘 익은 것도 있지만, 아직 익지 않은 토마토들도 있을 수 있다. 보관 후 하루가 지나면, 익은 토마토들의 인접한 곳에 있는 익지 않은 토마토들은 익은 토마토의 영향을 받아 익게 된다. 하나의 토마토의 인접한 곳은 왼쪽, 오른쪽, 앞, 뒤 네 방향에 있는 토마토를 의미한다. 대각선 방향에 있는 토마토들에게는 영향을 주지 못하며, 토마토가 혼자 저절로 익는 경우는 없다고 가정한다. 철수는 창고에 보관된 토마토들이 며칠이 지나면 다 익게 되는지, 그 최소 일수를 알고 싶어 한다.

토마토를 창고에 보관하는 격자모양의 상자들의 크기와 익은 토마토들과 익지 않은 토마토들의 정보가 주어졌을 때, 며칠이 지나면 토마토들이 모두 익는지, 그 최소 일수를 구하는 프로그램을 작성하라. 단, 상자의 일부 칸에는 토마토가 들어있지 않을 수도 있다.

# 입력
첫 줄에는 상자의 크기를 나타내는 두 정수 M,N이 주어진다. M은 상자의 가로 칸의 수, N은 상자의 세로 칸의 수를 나타낸다. 단, 2 ≤ M,N ≤ 1,000 이다. 둘째 줄부터는 하나의 상자에 저장된 토마토들의 정보가 주어진다. 즉, 둘째 줄부터 N개의 줄에는 상자에 담긴 토마토의 정보가 주어진다. 하나의 줄에는 상자 가로줄에 들어있는 토마토의 상태가 M개의 정수로 주어진다. 정수 1은 익은 토마토, 정수 0은 익지 않은 토마토, 정수 -1은 토마토가 들어있지 않은 칸을 나타낸다.

토마토가 하나 이상 있는 경우만 입력으로 주어진다.

# 출력
여러분은 토마토가 모두 익을 때까지의 최소 날짜를 출력해야 한다. 만약, 저장될 때부터 모든 토마토가 익어있는 상태이면 0을 출력해야 하고, 토마토가 모두 익지는 못하는 상황이면 -1을 출력해야 한다.

## 예제 입력 1 
```
6 4
0 0 0 0 0 0
0 0 0 0 0 0
0 0 0 0 0 0
0 0 0 0 0 1
```
## 예제 출력 1 
`8`

## 예제 입력 2 
```
6 4
0 -1 0 0 0 0
-1 0 0 0 0 0
0 0 0 0 0 0
0 0 0 0 0 1
```
## 예제 출력 2 
`-1`

## 예제 입력 3 
```
6 4
1 -1 0 0 0 0
0 -1 0 0 0 0
0 0 0 0 -1 0
0 0 0 0 -1 1
```

## 예제 출력 3 
`6`

## 예제 입력 4 
```
5 5
-1 1 0 0 0
0 -1 -1 -1 0
0 -1 -1 -1 0
0 -1 -1 -1 0
0 0 0 0 0
```
## 예제 출력 4 
`14`

## 예제 입력 5 
```
2 2
1 -1
-1 1
```

## 예제 출력 5 
`0`

**Comment by saokiritoni** [comment]
```java
package day_20;

import java.io.*;
import java.util.*;


public class baek_7576 {
	
	public static void main(String[] args) throws IOException {
		// TODO Auto-generated method stub
		BufferedReader br = new BufferedReader(new InputStreamReader(System.in));
		String line = br.readLine();
        
        // StringTokenizer를 사용하여 공백을 기준으로 문자열을 분리합니다.
        StringTokenizer st = new StringTokenizer(line, " ");
        
        // 분리된 문자열을 정수로 변환하여 저장합니다.
        int N = Integer.parseInt(st.nextToken()); // 열 
        int M = Integer.parseInt(st.nextToken()); // 행 
        
        // 토마토 상자 
        int[][] box = new int[M][N];
        
        // 익은 토마토 위치 
        Queue<int[]> tomato = new LinkedList<>();
        for (int i = 0; i < M; i++) { // 행에 대한 반복
            st = new StringTokenizer(br.readLine(), " ");
            for (int j = 0; j < N; j++) { // 열에 대한 반복
                box[i][j] = Integer.parseInt(st.nextToken());
                // 이미 익은 토마토라면 큐에 추가
                if (box[i][j] == 1) {
                    tomato.add(new int[]{i, j});
                }
            }
        }
       
        if (!tomato.isEmpty()) {
            int[] position = tomato.peek(); // 큐에서 맨 앞의 위치를 가져옵니다.
            int row = position[0]; // 행 위치
            int col = position[1]; // 열 위치
            System.out.println("Row: " + row + ", Col: " + col);
        } else {
            System.out.println("Queue is empty"); // 결과: [3, 5] => 네번째행 여섯번째 
        }


	}

}

```

일단 box에서 익은 토마토의 위치를 저장하는 tomato 큐를 만드는 것까지 했다. 
<img width="121" alt="스크린샷 2024-01-31 오후 12 18 16" src="https://github.com/GoormPyri/GoormPyri/assets/144209738/d58f707f-1d6b-49fb-bc34-15fd36b7fbf3">


<img width="146" alt="스크린샷 2024-01-31 오후 12 18 34" src="https://github.com/GoormPyri/GoormPyri/assets/144209738/fe951693-3959-4b2e-9ae7-a7082dad3902">

<img width="121" alt="스크린샷 2024-01-31 오후 12 19 29" src="https://github.com/GoormPyri/GoormPyri/assets/144209738/6997ffee-2f34-4e53-b87c-cdc22bd96901">

**Comment by saokiritoni** [comment]
Do it 코딩테스트 5장 탐색-문제 027(미로 탐색하기) p.169 (자바 편 기준) 해답 코드를 모방해서 작성했어요. 미로 탐색 코드에서 토마토를 우겨넣고 잘못된 부분 수정하는 식으로 하다보니까 아직 완전히 이해는 안 갔어요. 어쨌든 통과되었습니다...! 상하좌우 이동을 dx, dy 배열을 통해 움직이는 아이디어가 포인트인 거 같아요. 

# 1) tomato, box 코드
box: 토마토 상자 박스 (입력받은 배열)
tomato: 이미 익은 토마토의 박스 인덱스 위치가 저장됨.
추가) day: 익는 데에 걸린 일수가 저장된 배열
```java
Queue<int[]> tomato = new LinkedList<>();
        for (int i = 0; i < M; i++) { // 행에 대한 반복
            st = new StringTokenizer(br.readLine(), " ");
            for (int j = 0; j < N; j++) { // 열에 대한 반복
                box[i][j] = Integer.parseInt(st.nextToken());
                // 이미 익은 토마토라면 큐에 추가
                if (box[i][j] == 1) {
                    tomato.add(new int[]{i, j});
                }
            }
        }
```


# 2) BFS 코드
```java
static int[] dx = {-1, 1, 0, 0}; // 상, 하 이동 
static int[] dy = {0, 0, -1, 1}; // 좌, 우 이동 
```
```java
        // BFS
        while (!tomato.isEmpty()) { // tomato 큐가 비어있을 때까지 
        	int now[] = tomato.poll(); // front 확인&삭제 
        	for (int i = 0; i < 4; i++) { // 상하좌우 check 
        		int x = now[0] + dx[i]; // 행 index
        		int y = now[1] + dy[i]; // 열 index 
        		if (x >= 0 && y >= 0 && x < M && y < N) { // 배열의 범위 넘어가지 않도록 조정 
        			if(box[x][y] == 0) {
        				box[x][y] = 1; // 익은 토마토로 바꾸기 
        				tomato.add(new int[] {x,y}); // 익은 토마토 위치 다시 저장 
        				day[x][y] = day[now[0]][now[1]] + 1; //  day+1 업데이트 
        				
        			}
        		}
        	}
        }
```
# 3) 완성 코드 
```java
package day_20;

import java.io.*;
import java.util.*;


public class baek_7576 {
	static int[] dx = {-1, 1, 0, 0}; // 상, 하 이동 
	static int[] dy = {0, 0, -1, 1}; // 좌, 우 이동 
	
	public static void main(String[] args) throws IOException {
		// TODO Auto-generated method stub
		BufferedReader br = new BufferedReader(new InputStreamReader(System.in));
		String line = br.readLine();
        
       
        StringTokenizer st = new StringTokenizer(line, " ");
        
        
        int N = Integer.parseInt(st.nextToken()); // 열 
        int M = Integer.parseInt(st.nextToken()); // 행 
        
        // 토마토 상자 box
        int[][] box = new int[M][N];
        
        // 익은 토마토 위치가 저장된 tomato 큐 
        Queue<int[]> tomato = new LinkedList<>();
        for (int i = 0; i < M; i++) { // 행에 대한 반복
            st = new StringTokenizer(br.readLine(), " ");
            for (int j = 0; j < N; j++) { // 열에 대한 반복
                box[i][j] = Integer.parseInt(st.nextToken());
                // 이미 익은 토마토라면 큐에 추가
                if (box[i][j] == 1) {
                    tomato.add(new int[]{i, j});
                }
            }
        }
        // 익는데 걸린 일수 배열 day 
        int [][] day = new int[M][N];
        
        // BFS
        while (!tomato.isEmpty()) { // tomato 큐가 비어있을 때까지 
        	int now[] = tomato.poll(); // front 확인&삭제 
        	for (int i = 0; i < 4; i++) { // 상하좌우 check 
        		int x = now[0] + dx[i]; // 행 index
        		int y = now[1] + dy[i]; // 열 index 
        		if (x >= 0 && y >= 0 && x < M && y < N) { // 배열의 범위 넘어가지 않도록 조정 
        			if(box[x][y] == 0) {
        				box[x][y] = 1; // 익은 토마토로 바꾸기 
        				tomato.add(new int[] {x,y}); // 익은 토마토 위치 다시 저장 
        				day[x][y] = day[now[0]][now[1]] + 1; //  day+1 업데이트 
        				
        			}
        		}
        	}
        }
        
        int maxDay = 0; // 모든 토마토가 익는데 걸린 최대 일수
        boolean allRipe = true; // 모든 토마토가 익었는지 여부

        for (int i = 0; i < M; i++) { 
            for (int j = 0; j < N; j++) { 
                if (box[i][j] == 0) {
                    allRipe = false; // 익지 않은 토마토가 존재
                    break;
                }
                maxDay = Math.max(maxDay, day[i][j]);
            }
            if (!allRipe) break;
        }

        if (allRipe) {
            System.out.println(maxDay); // 모든 토마토가 익는데 걸린 최대 일수 출력
        } else {
            System.out.println(-1); // 익지 않은 토마토가 있으므로 -1 출력
        }
      


	}

}

```

**Comment by GEONHO96** [comment]
소은이와 다르게 저는 BufferedReader가 아닌 Scanner를 이용해서 문제를 풀었습니다.
Do it 알고리즘 코딩테스트 자바 편에서 보니까 이 문제는 BFS(너비 우선 탐색)을 이용한 풀이더라구요. 비록 다 풀지 못했지만 일부 코드를 가져오긴 했습니다.

package day20;

import java.util.LinkedList;
import java.util.Queue;
import java.util.Scanner;

public class P7576_토마토 {
    static int[] dx = {-1, 1, 0, 0}; // 상하좌우 이동을 위한 배열
    static int[] dy = {0, 0, -1, 1};

    public static void main(String[] args) {
        Scanner sc = new Scanner(System.in);

        int M = sc.nextInt(); // 상자의 가로 칸 수
        int N = sc.nextInt(); // 상자의 세로 칸 수

        int[][] box = new int[N][M]; // 토마토 상태를 저장하는 상자
        Queue<int[]> queue = new LinkedList<>(); // BFS를 위한 큐

        // 상자 초기화 및 익은 토마토의 위치를 큐에 추가
        for (int i = 0; i < N; i++) {
            for (int j = 0; j < M; j++) {
                box[i][j] = sc.nextInt();
                if (box[i][j] == 1) {
                    queue.offer(new int[]{i, j, 0}); // 익은 토마토의 위치와 날짜 정보를 큐에 추가
                }
            }
        }

        int days = ripenTomatoes(box, queue, N, M);

        System.out.println(days);
    }

    private static int ripenTomatoes(int[][] box, Queue<int[]> queue, int N, int M) {
        
    }
}

**Comment by GEONHO96** [comment]
소은이와 다르게 저는 BufferedReader가 아닌 Scanner를 이용해서 문제를 풀었습니다.
Do it 알고리즘 코딩테스트 자바 편에서 보니까 이 문제는 BFS(너비 우선 탐색)을 이용한 풀이더라구요. 비록 다 풀지 못했지만 일부 코드를 가져오긴 했습니다.



package day20;

import java.util.LinkedList;
import java.util.Queue;
import java.util.Scanner;

public class P7576_토마토 {
    static int[] dx = {-1, 1, 0, 0}; // 상하좌우 이동을 위한 배열
    static int[] dy = {0, 0, -1, 1};

    public static void main(String[] args) {
        Scanner sc = new Scanner(System.in);

        int M = sc.nextInt(); // 상자의 가로 칸 수
        int N = sc.nextInt(); // 상자의 세로 칸 수

        int[][] box = new int[N][M]; // 토마토 상태를 저장하는 상자
        Queue<int[]> queue = new LinkedList<>(); // BFS를 위한 큐

        // 상자 초기화 및 익은 토마토의 위치를 큐에 추가
        for (int i = 0; i < N; i++) {
            for (int j = 0; j < M; j++) {
                box[i][j] = sc.nextInt();
                if (box[i][j] == 1) {
                    queue.offer(new int[]{i, j, 0}); // 익은 토마토의 위치와 날짜 정보를 큐에 추가
                }
            }
        }

        int days = ripenTomatoes(box, queue, N, M);

        System.out.println(days);
    }

    private static int ripenTomatoes(int[][] box, Queue<int[]> queue, int N, int M) {

    }
}

**Comment by GEONHO96** [comment]
소은이와 다르게 저는 BufferedReader가 아닌 Scanner를 이용해서 문제를 풀었습니다.
Do it 알고리즘 코딩테스트 자바 편에서 보니까 이 문제는 BFS(너비 우선 탐색)을 이용한 풀이더라구요. 비록 다 풀지 못했지만 일부 코드를 가져오긴 했습니다.

**Comment by GEONHO96** [comment]
package day20;

import java.util.LinkedList;
import java.util.Queue;
import java.util.Scanner;

public class P7576_토마토 {
    static int[] dx = {-1, 1, 0, 0}; // 상하좌우 이동을 위한 배열
    static int[] dy = {0, 0, -1, 1};

    public static void main(String[] args) {
        Scanner sc = new Scanner(System.in);

        int M = sc.nextInt(); // 상자의 가로 칸 수
        int N = sc.nextInt(); // 상자의 세로 칸 수

        int[][] box = new int[N][M]; // 토마토 상태를 저장하는 상자
        Queue<int[]> queue = new LinkedList<>(); // BFS를 위한 큐

        // 상자 초기화 및 익은 토마토의 위치를 큐에 추가
        for (int i = 0; i < N; i++) {
            for (int j = 0; j < M; j++) {
                box[i][j] = sc.nextInt();
                if (box[i][j] == 1) {
                    queue.offer(new int[]{i, j, 0}); // 익은 토마토의 위치와 날짜 정보를 큐에 추가
                }
            }
        }

        int days = ripenTomatoes(box, queue, N, M);

        System.out.println(days);
    }

    private static int ripenTomatoes(int[][] box, Queue<int[]> queue, int N, int M) {

    }
}

**Comment by GEONHO96** [comment]
private static int ripenTomatoes(int[][] box, Queue<int[]> queue, int N, int M) {

}
여기 안에 코드를 어떻게 작성할 지 몰라서 그런데 팀원들이랑 같이 의논해보고 싶습니다.

**Comment by GEONHO96** [comment]
```java
```
package day20;

import java.util.LinkedList;
import java.util.Queue;
import java.util.Scanner;

public class P7576_토마토 {
static int[] dx = {-1, 1, 0, 0}; // 상하좌우 이동을 위한 배열
static int[] dy = {0, 0, -1, 1};

public static void main(String[] args) {
    Scanner sc = new Scanner(System.in);

    int M = sc.nextInt(); // 상자의 가로 칸 수
    int N = sc.nextInt(); // 상자의 세로 칸 수

    int[][] box = new int[N][M]; // 토마토 상태를 저장하는 상자
    Queue<int[]> queue = new LinkedList<>(); // BFS를 위한 큐

    // 상자 초기화 및 익은 토마토의 위치를 큐에 추가
    for (int i = 0; i < N; i++) {
        for (int j = 0; j < M; j++) {
            box[i][j] = sc.nextInt();
            if (box[i][j] == 1) {
                queue.offer(new int[]{i, j, 0}); // 익은 토마토의 위치와 날짜 정보를 큐에 추가
            }
        }
    }

    int days = ripenTomatoes(box, queue, N, M);

    System.out.println(days);
}

private static int ripenTomatoes(int[][] box, Queue<int[]> queue, int N, int M) {

}
}

**Comment by GEONHO96** [comment]
```java
package day20;

import java.util.LinkedList;
import java.util.Queue;
import java.util.Scanner;

public class P7576_토마토 {
    static int[] dx = {-1, 1, 0, 0}; // 상하좌우 이동을 위한 배열
    static int[] dy = {0, 0, -1, 1};

    public static void main(String[] args) {
        Scanner sc = new Scanner(System.in);

        int M = sc.nextInt(); // 상자의 가로 칸 수
        int N = sc.nextInt(); // 상자의 세로 칸 수

        int[][] box = new int[N][M]; // 토마토 상태를 저장하는 상자
        Queue<int[]> queue = new LinkedList<>(); // BFS를 위한 큐

        // 상자 초기화 및 익은 토마토의 위치를 큐에 추가
        for (int i = 0; i < N; i++) {
            for (int j = 0; j < M; j++) {
                box[i][j] = sc.nextInt();
                if (box[i][j] == 1) {
                    queue.offer(new int[]{i, j, 0}); // 익은 토마토의 위치와 날짜 정보를 큐에 추가
                }
            }
        }

        int days = ripenTomatoes(box, queue, N, M);

        System.out.println(days);
    }

    private static int ripenTomatoes(int[][] box, Queue<int[]> queue, int N, int M) {

    }
}
```

**Comment by potatoj1n** [comment]
🤔 생각해야할 점
1. 정수 1은 익은 토마토, 0은 익지 않은 토마토, -1은 토마토가 들어있지 않은 칸을 의미
2. 보관한 지 하루가 지나면 익은 토마토에 인접한 토마토들도 익게 된다.
    
    ( 1에 인접한 0들이 1이 된다. 인접의 기준: 앞 뒤 오른쪽 왼쪽 4방향)
    
3. 토마토가 없는 칸도 존재한다. 
4. 토마토가 모두 익을 때까지의 최소 날짜를 출력하는데 만약 처음부터 모든 토마토가 익어있다면 0을 토마토가 모두 익을 수 없는 상황이면 -1 출력

🔥 풀이 과정

1. N,M,토마토 배열 입력받기
2. 익은 토마토 (1인 토마토)를 큐에 넣어서 인접한 토마토들 검사
3. 한번 반복이 끝나면 날짜 수를 올려주고 다시 반복
4. 1이 있는데 0이 없다→ 토마토가 전부 익은채로 들어왔다 ( 0 리턴) 📍(이부분을 구현을 못해서 틀린듯)
5. 전부 다 검사하고 큐가 비어있으면 종료 → 여전히 0인 토마토가 있으면 -1 리턴
```cpp
#include<iostream>
#include<queue>
using namespace std;

int main(){
    //입력 받기
    int N,M;
    cin >> N >> M;
    queue<pair<int,int>> q;
    int day = 0;
    //토마토 배열 입력
    int arr[1000][1000];
    for(int i = 0; i < N; i++)
        for(int j=0; j < M; j++){
            cin >> arr[i][j];
            if(arr[i][j] == 1) {
                q.push({i, j}); // 익은 토마토의 좌표를 큐에 넣는다.
            }
        }
   //큐에 넣은 익은 토마토들에 인접한 토마토들 익도록 
    while(!q.empty()){
        int size = q.size(); // 현재 익은 토마토의 개수만큼 BFS를 진행
        day++; // 일수 증가

        for(int i = 0; i < size; i++) {
            int x = q.front().first;//큐 맨앞 요소->x좌표
            int y = q.front().second;//큐 맨앞 요소 -> y좌표
            q.pop();

            int dx[4] = {-1, 1, 0, 0}; // 범위에 맞게 상하좌우 이동을 위한 배열
            int dy[4] = {0, 0, -1, 1};

            for(int j = 0; j < 4; j++) { // 상하좌우 이동
                int nx = x + dx[j];
                int ny = y + dy[j];

                if(nx >= 0 && nx < N && ny >= 0 && ny < M && arr[nx][ny] == 0) { // 범위 내에 있고 익지 않은 토마토일 때
                    arr[nx][ny] = 1; // 토마토 익힘
                    q.push({nx, ny}); // 인접한 익지 않은 토마토의 좌표를 큐에 넣음(이제 익은 토마토)
                }
            }
        }
    }
    
    // 모든 토마토가 익은 상태인지 확인
    for(int i = 0; i < N; i++)
        for(int j = 0; j < M; j++)
            if(arr[i][j] == 0) { // 익지 않은 토마토가 있는 경우
                cout << -1 << endl;
                return 0;
            }
   cout << day -1 <<endl; 
  return 0;  
}
```

**Comment by hyeyoooo** [comment]
```c++
#include <bits/stdc++.h>
#include <vector>
#include <queue>

using namespace std;

struct tomato{
    int y, x;
};

int dx[4] = {0, 0, -1, 1};
int dy[4] = {-1, 1, 0, 0};

int m, n;
int box[1001][1001];
queue<tomato> q;

bool is_inside(int ny, int nx){
    return (0 <= ny && ny < n && 0 <= nx && nx < m);
}

void bfs(void){
    
    while(!q.empty()){
        int y = q.front().y;
        int x = q.front().x;
        q.pop();

        for(int i=0; i<4; i++){
            int ny = y + dy[i];
            int nx = x + dx[i];
	   if(is_inside(ny,nx) == 1 && box[ny][nx] == 1) {
	   box[ny][nx] = box[y][x] + 1;
		}
        }
    }
}
int main(){

    cin >> m >> n;
    
        for(int i=0; i<n; i++){
        for(int j=0; j<m; j++){
            cin >> box[i][j];
            if(box[i][j] == 1) q.push({i, j});
                    }
    }         
```

**Comment by saokiritoni** [comment]
# 멘토링 결과
```cc
#include <iostream>
#include <vector>
#include <queue>
using namespace std;
class Point;
int M, N;
int maxVal;
vector<vector<int>> arr;
queue<Point> q;
int count;
int ex;
class Point {
public:
    int x;
    int y;
    Point() {};
    Point(int x, int y) : x(x), y(y) {}
};
void bfs() {
    Point tmp;
    while (!q.empty()) {
        tmp = q.front();
        q.pop();
        maxVal = arr[tmp.x][tmp.y] > maxVal ? arr[tmp.x][tmp.y] : maxVal;
        count++;
        if (tmp.x + 1 <= N && arr[tmp.x + 1][tmp.y] != -1 && arr[tmp.x + 1][tmp.y] == 0) {
            q.push(Point(tmp.x + 1, tmp.y));
            arr[tmp.x + 1][tmp.y] = arr[tmp.x][tmp.y] + 1;
        }
        if (tmp.x - 1 > 0 && arr[tmp.x - 1][tmp.y] != -1 && arr[tmp.x - 1][tmp.y] == 0) {
            q.push(Point(tmp.x - 1, tmp.y));
            arr[tmp.x - 1][tmp.y] = arr[tmp.x][tmp.y] + 1;
        }
        if (tmp.y + 1 <= M && arr[tmp.x][tmp.y + 1] != -1 && arr[tmp.x][tmp.y + 1] == 0) {
            q.push(Point(tmp.x, tmp.y + 1));
            arr[tmp.x][tmp.y + 1] = arr[tmp.x][tmp.y] + 1;
        }
        if (tmp.y - 1 > 0 && arr[tmp.x][tmp.y - 1] != -1 && arr[tmp.x][tmp.y - 1] == 0) {
            q.push(Point(tmp.x, tmp.y - 1));
            arr[tmp.x][tmp.y - 1] = arr[tmp.x][tmp.y] + 1;
        }
    }
}
int main() {
    int tmp;
    cin >> M >> N;
    arr.resize(N + 1, vector<int>(M + 1, 0));
    for (int i = 1; i <= N; i++) {
        for (int j = 1; j <= M; j++) {
            cin >> tmp;
            arr[i][j] = tmp;
            if (tmp == 1) {
                q.push(Point(i, j));
            } else if (tmp == -1) {
                ex++;
            }
        }
    }
    bfs();
    cout << ((count + ex) == M * N ? maxVal - 1 : -1) << endl;
    return 0;
}
```
